### ISSUE TITLE
Sign in broken

### ISSUE THREAD

**Issue by dtolb** [BandwidthExamples/node-web-phone#2]
After 1 click deploy to heroku:
https://whispering-crag-64643.herokuapp.com/signin

![screen shot 2016-03-10 at 2 47 57 pm](https://cloud.githubusercontent.com/assets/6805534/13682302/3269d21c-e6cf-11e5-9386-57bc187fd657.png)

**Comment by avbel** [comment]
This is limitaion of 16 symbols for domain names in catapult. `whispering-crag-64643` has length more than 16 symbols. You should use mre short domain name in heroku. I'll fix this issue in code (to use heroku without any limiations)

**Comment by avbel** [comment]
Done. I had to make changes in `master` because there is an issue with 1-click deploy to heroku from other branches. Now I check domain name from code and truncate it if need
