### ISSUE TITLE
When logging in with new credentials, the domain is already taken

### ISSUE THREAD

**Issue by dtolb** [BandwidthExamples/node-web-phone#6]
Logging in to the same instance creates the same domain on separate catapult accounts. The 2nd+ user can not use :(

**Comment by avbel** [comment]
Yes. This is "feature" of catapult. All domain names should be unique for all users. I.e. if one user creates domain `domain1` nobody will able to create domain with such name more. It will be good to add to Catapult api to check if domain can be used.
I'll think how to avoid this problem here
